permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Jason
  email: hzqingzz@gmail.com
  link: http://qingzz.github.io
#  weibo: 
  github: http://github.com/qingzz

# 站点信息
title: 迷津渡口
description: 破迷津 通道境
url: http://qingzz.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-70604753-1
  url: qingzz.github.io

# disqus 设置
disqus:
  shortname: qingzz
